### ISSUE TITLE
HD is ignored in simulate command for taiko and catch

### ISSUE THREAD

**Issue by Cyan903** [ppy/osu-tools#153] opened 2022-06-18 04:15 UTC
#150 fixes HD for std:
![osu](https://user-images.githubusercontent.com/88910588/174421563-044c40b6-f25b-42f8-a727-3b37fc3aa14f.png)

But taiko and catch still don't show hidden.
![taiko](https://user-images.githubusercontent.com/88910588/174421595-4bd5c10d-51f8-440e-a9a4-a0905cae9a53.png)
![catch](https://user-images.githubusercontent.com/88910588/174421596-4f785de1-e2e4-497f-bc17-7df7d32d68b6.png)

It isn't just visual either, the pp is calculated as if the score didn't have hidden enabled.

**Comment by smoogipoo** [comment] 2022-06-18 04:30
I encountered this also earlier today, and found it's also ignored for mania. It's caused by this:
https://github.com/ppy/osu-tools/blob/504f24ed724c98d25e77d031c2c6bf1002d3c623/PerformanceCalculator/LegacyHelper.cs#L83-L87

I believe the reason #150 fixed #149 is because HD became a difficulty adjustment mod.

Mods shouldn't be ignored for PP calculation at all.

**Comment by Cyan903** [comment] 2022-06-23 08:39
Not sure if I should open another issue, but I did some further testing and it seems that it isn't just hidden, multiple taiko mods aren't calculating properly.

Using [this](https://osu.ppy.sh/beatmapsets/1351158#taiko/2892205) map as an example:

#### For HR:
```sh
dotnet run --project ./PerformanceCalculator/ -- simulate taiko 2892205 -a 100 -c 490 -X 0 -m hr
# pp: 300.91
```
Output: https://pastebin.com/hQmGrqNU
Yet comparing that to a [score set on bancho](https://osu.ppy.sh/scores/taiko/161819420), there is nearly a 20pp difference.


#### For DT:
```sh
dotnet run --project ./PerformanceCalculator/ -- simulate taiko 2892205 -a 99.08 -c 490 -X 0 -m dt
# pp: 485.60
```
Output: https://pastebin.com/y0qyKchu
Compared to [another bancho score](https://osu.ppy.sh/scores/taiko/161574805), a difference of 103pp.


#### For FL:
(2892205 didn't have any FL plays so I'm using [this](https://osu.ppy.sh/beatmapsets/712757#taiko/1519305) as an example)
```sh
dotnet run --project ./PerformanceCalculator/ -- simulate taiko 1519305 -a 99.52 -c 943 -X 0 -m fl
# pp: 304.29
```
Output: https://pastebin.com/Dptwvc5A
15pp diff from [here](https://osu.ppy.sh/scores/taiko/167612992). Also FL is being ignored as a mod here.


EZ, NF, and HT also have a difference, but it's usually in the single digits so I don't think it's a huge deal. HR is mostly functional with it only being around 20-40pp off. It's mainly DT, HD, and FL that have issues. I tested all of these on the latest commit which was [9 days ago at the time of writing this](https://github.com/ppy/osu-tools/commit/504f24ed724c98d25e77d031c2c6bf1002d3c623).

**Comment by smoogipoo** [comment] 2022-06-23 09:03
Diffcalc/ppcalc is constantly evolving and this tool (for the most part) tracks the most recent changes. https://github.com/ppy/osu/pull/18208 was merged since the last deploy which is included in the latest master.

There are still some differences (<5pp from my testing) and those could come down to any non-diffcalc fixes that happened in the last however-long-it's-been-since-deploy that could have affected things (e.g. fixes to beatmap parsing). Or it could be related to sometimes ppcalc on osu-web just misses scores - I forget the exact cause.

What I can tell you with certainty though, is that the current changes in `master` match the current osu-performance on those scores.

The only ones of relevance that don't match are FL, HD, and NF, because those mods are skipped via the same reasoning as above.

**Closed** 2024-03-05 19:14 UTC
