### ISSUE TITLE
Memory leak while calculating some mania beatmaps

### ISSUE THREAD

**Issue by b11p** [ppy/osu-tools#28] opened 2019-03-01 02:19 UTC
The beatmap was https://osu.ppy.sh/beatmapsets/331833#mania/745327
I ran `dotnet .\PerformanceCalculator.dll difficulty "C:\Users\yinmi\Downloads\331833 Electric Joy Ride & Fusk Asker - Coco\Electric Joy Ride & Fusk Asker - Coco (c36098651) [BPM0].osu"` in pwsh and PerformanceCalculator was going to eat all my memory, not stopping. I had to stop it using Ctrl+C.

![image](https://user-images.githubusercontent.com/35132976/53611845-e6247800-3c0a-11e9-94ca-fbf1dcacc106.png)

**Comment by peppy** [comment] 2019-03-01 02:26
Interesting. Can't reproduce high memory usage when just running through the beatmap in lazer, so must be something specific to difficulty calculation.

**Comment by smoogipoo** [comment] 2021-05-31 10:57
This is intended. I think it's since been addressed by a 10s beatmap load timeout (can't remember it if existed back in 2019), but the underlying issue is that difficulty calculation has its control point limiters removed.

If you're interested in a local deploy and don't care about accuracy for edge cases (like BPM0) remove this line:
https://github.com/ppy/osu-tools/blob/f41cf7382e5fa8f850a4f2433639932f5c975f5c/PerformanceCalculator/Program.cs#L24

**Closed by smoogipoo** 2021-05-31 10:57 UTC
